import { Inter } from "next/font/google";
import localFont from "next/font/local";
import { AppProvider } from "@/components/AppContext";
import "./globals.css";
import Header from '@/components/layout/Header';
import Footer from '@/components/layout/Footer';
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

const dana = localFont({
  src: [
    {
      path: '../../public/fonts/Dana Font/DanaFaNum-Light.ttf',
      weight: '100',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Dana Font/DanaFaNum-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Dana Font/DanaFaNum-Medium.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Dana Font/DanaFaNum-DemiBold.ttf',
      weight: '600',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Dana Font/DanaFaNum-Bold.ttf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Dana Font/DanaFaNum-ExtraBold.ttf',
      weight: '800',
      style: 'normal',
    },
    {
      path: '../../public/fonts/Dana Font/DanaFaNum-ExtraBlack.ttf',
      weight: '900',
      style: 'normal',
    },
  ]
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir="rtl" className="scroll-smooth">
      <body className={dana.className}>
        <main className="max-w-6xl mx-auto p-4">
          <AppProvider>
            <Toaster />
            <Header />
            {children}
            <Footer />
          </AppProvider>
        </main>
      </body>
    </html>
  );
}
